### ISSUE TITLE
section two

### ISSUE THREAD

**Issue by talaalsweiti** [gsg-K1-FC/project6#3]

**Comment by waed-hamza** [comment]
Create the second section "Services Section"

Two div:
1. Design And Plan Your Business Growth Steps.
2. Search For Optimization Wherever Is Possible.

**Comment by waed-hamza** [comment]
Create the second section "Services Section"

Two div:

1. Design And Plan Your Business Growth Steps.
2. Search For Optimization Wherever Is Possible.
